### ISSUE TITLE
Excellent contribution!

### ISSUE THREAD

**Issue by sebito91** [beeceej/sls-go-examples#1]
Would you like to submit your solution as an official example in the `serverless/examples` repo?

https://github.com/serverless/examples/issues/290

Seems like we're on the same page!

**Comment by beeceej** [comment]
@sebito91 I Just saw this, but that sounds awesome! 

I'd like to clean up some of the setup documentation (especially for the elastic search / Dynamo example.

I'll take that issue, and create a PR once the documentation is up to par!

**Comment by sebito91** [comment]
Wonderful, thanks a bunch. Really excited to get that into the repo, and thanks again for the contribution!

**Comment by beeceej** [comment]
@sebito91 please let me know if you have suggestions.

https://github.com/serverless/examples/pull/296

**Comment by beeceej** [comment]
This was merged upstream!
